production:
  adapter: postgresql
  database: discourse
  username: discourse
  password: {{ pillar["discourse"]["postgresql_password"] }}
  pool: 5       # size of DB connection pool *per process*
  timeout: 5000
  db_id: 0    # database ID if hosting multiple sites
  host_names:
    - forum.makeheadspace.com
    - hedgehog.makeheadspace.com

test:
  adapter: postgresql
  database: discourse_test
  min_messages: warning
  host: localhost
  pool: 5
  timeout: 5000
  host_names:
    - test.forum.makeheadspace.com
    - test.hedgehog.makeheadspace.com
